"""
SlideToHtmlHandler contains all business logic for slide-to-html, html-to-react, and template management operations.
Uses mixins for common functionality like database operations, logging, and validation.
"""

import os
import base64
from datetime import datetime
from typing import Optional, List, Dict

from fastapi import HTTPException, UploadFile
from openai import OpenAI, APIError
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, delete, func

# Models
from models.sql.presentation_layout_code import PresentationLayoutCodeModel
from models.sql.template import TemplateModel

# Services and utilities
from utils.asset_directory_utils import get_images_directory

# Mixins
from mixins import DatabaseMixin, ValidationMixin


class SlideToHtmlHandler(DatabaseMixin, ValidationMixin):
    """Handler for all slide-to-html, html-to-react, and template management operations."""
    
    def __init__(self, sql_session: AsyncSession):
        super().__init__(sql_session)
        self.log_request_start("handler_initialization", handler="SlideToHtmlHandler")
    
    async def generate_html_from_slide(
        self, 
        base64_image: str, 
        media_type: str, 
        xml_content: str, 
        api_key: str, 
        fonts: Optional[List[str]] = None
    ) -> str:
        """
        Generate HTML content from slide image and XML using OpenAI GPT-5.
        
        Args:
            base64_image: Base64 encoded image data
            media_type: MIME type of the image
            xml_content: OXML content as text
            api_key: OpenAI API key
            fonts: Optional list of normalized root font families
            
        Returns:
            Generated HTML content as string
        """
        self.log_external_service_call("OpenAI", "generate_html_from_slide")
        
        try:
            client = OpenAI(api_key=api_key)

            # Compose input for Responses API
            data_url = f"data:{media_type};base64,{base64_image}"
            fonts_text = f"\nFONTS (Normalized root families used in this slide, use where it is required): {', '.join(fonts)}" if fonts else ""
            user_text = f"OXML: \n\n{fonts_text}"
            
            # Import the system prompt here to avoid circular imports
            from api.v1.ppt.endpoints.prompts import GENERATE_HTML_SYSTEM_PROMPT
            
            input_payload = [
                {"role": "system", "content": GENERATE_HTML_SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": [
                        {"type": "input_image", "image_url": data_url},
                        {"type": "input_text", "text": user_text},
                    ],
                },
            ]

            self.logger.debug("Making OpenAI API request for HTML generation")
            response = client.responses.create(
                model="gpt-5",
                input=input_payload,
                reasoning={"effort": "high"},
                text={"verbosity": "low"},
            )

            html_content = getattr(response, "output_text", None) or getattr(response, "text", None) or ""
            
            self.logger.info("Generated HTML content", content_length=len(html_content))
            
            if not html_content:
                self.log_external_service_error("OpenAI", "generate_html", "No HTML content generated")
                raise HTTPException(
                    status_code=500,
                    detail="No HTML content generated by OpenAI GPT-5"
                )
            
            return html_content
            
        except APIError as e:
            self.log_external_service_error("OpenAI", "generate_html", str(e))
            raise HTTPException(
                status_code=500,
                detail=f"OpenAI API error during HTML generation: {str(e)}"
            )
        except Exception as e:
            error_msg = str(e)
            self.logger.exception("Failed to generate HTML from slide", error_type=type(e).__name__)
            
            if "timeout" in error_msg.lower():
                raise HTTPException(
                    status_code=408,
                    detail=f"OpenAI API timeout during HTML generation: {error_msg}"
                )
            elif "connection" in error_msg.lower():
                raise HTTPException(
                    status_code=503,
                    detail=f"OpenAI API connection error during HTML generation: {error_msg}"
                )
            else:
                raise HTTPException(
                    status_code=500,
                    detail=f"OpenAI API error during HTML generation: {error_msg}"
                )

    async def generate_react_component_from_html(
        self, 
        html_content: str, 
        api_key: str, 
        image_base64: Optional[str] = None, 
        media_type: Optional[str] = None
    ) -> str:
        """
        Convert HTML content to TSX React component using OpenAI GPT-5.
        
        Args:
            html_content: Generated HTML content
            api_key: OpenAI API key
            image_base64: Optional base64 image data
            media_type: Optional media type for image
            
        Returns:
            Generated TSX React component code as string
        """
        self.log_external_service_call("OpenAI", "generate_react_component")
        
        try:
            client = OpenAI(api_key=api_key)

            # Build payload with optional image
            content_parts = [{"type": "input_text", "text": f"HTML INPUT:\n{html_content}"}]
            if image_base64 and media_type:
                data_url = f"data:{media_type};base64,{image_base64}"
                content_parts.insert(0, {"type": "input_image", "image_url": data_url})

            from api.v1.ppt.endpoints.prompts import HTML_TO_REACT_SYSTEM_PROMPT
            
            input_payload = [
                {"role": "system", "content": HTML_TO_REACT_SYSTEM_PROMPT},
                {"role": "user", "content": content_parts},
            ]

            response = client.responses.create(
                model="gpt-5",
                input=input_payload,
                reasoning={"effort": "minimal"},
                text={"verbosity": "low"},
            )

            react_content = getattr(response, "output_text", None) or getattr(response, "text", None) or ""
            
            self.logger.info("Generated React content", content_length=len(react_content))
            
            if not react_content:
                self.log_external_service_error("OpenAI", "generate_react", "No React component generated")
                raise HTTPException(
                    status_code=500,
                    detail="No React component generated by OpenAI GPT-5"
                )
            
            # Clean up the generated content
            react_content = react_content.replace("```tsx", "").replace("```", "").replace("typescript", "").replace("javascript", "")

            # Filter out import/export lines
            filtered_lines = []
            for line in react_content.split('\n'):
                stripped_line = line.strip()
                if not (stripped_line.startswith('import ') or stripped_line.startswith('export ')):
                    filtered_lines.append(line)
            
            filtered_react_content = '\n'.join(filtered_lines)
            self.logger.debug("Filtered React content", filtered_length=len(filtered_react_content))
            
            return filtered_react_content
            
        except APIError as e:
            self.log_external_service_error("OpenAI", "generate_react", str(e))
            raise HTTPException(
                status_code=500,
                detail=f"OpenAI API error during React generation: {str(e)}"
            )
        except Exception as e:
            error_msg = str(e)
            self.logger.exception("Failed to generate React component", error_type=type(e).__name__)
            
            if "timeout" in error_msg.lower():
                raise HTTPException(
                    status_code=408,
                    detail=f"OpenAI API timeout during React generation: {error_msg}"
                )
            elif "connection" in error_msg.lower():
                raise HTTPException(
                    status_code=503,
                    detail=f"OpenAI API connection error during React generation: {error_msg}"
                )
            else:
                raise HTTPException(
                    status_code=500,
                    detail=f"OpenAI API error during React generation: {error_msg}"
                )

    async def edit_html_with_images(
        self, 
        current_ui_base64: str, 
        sketch_base64: Optional[str], 
        media_type: str, 
        html_content: str, 
        prompt: str, 
        api_key: str
    ) -> str:
        """
        Edit HTML content based on images and prompt using OpenAI GPT-5.
        
        Args:
            current_ui_base64: Base64 current UI image
            sketch_base64: Optional base64 sketch image
            media_type: Media type for images
            html_content: Current HTML content
            prompt: Edit instruction prompt
            api_key: OpenAI API key
            
        Returns:
            Edited HTML content as string
        """
        self.log_external_service_call("OpenAI", "edit_html_with_images")
        
        try:
            client = OpenAI(api_key=api_key)

            # Build content with images
            content_parts = []
            content_parts.append({"type": "input_image", "image_url": f"data:{media_type};base64,{current_ui_base64}"})
            
            if sketch_base64:
                content_parts.append({"type": "input_image", "image_url": f"data:{media_type};base64,{sketch_base64}"})
            
            content_parts.append({"type": "input_text", "text": f"HTML:\n{html_content}\n\nPROMPT: {prompt}"})

            from api.v1.ppt.endpoints.prompts import HTML_EDIT_SYSTEM_PROMPT
            
            input_payload = [
                {"role": "system", "content": HTML_EDIT_SYSTEM_PROMPT},
                {"role": "user", "content": content_parts},
            ]

            response = client.responses.create(
                model="gpt-5",
                input=input_payload,
                reasoning={"effort": "medium"},
                text={"verbosity": "low"},
            )

            edited_html = getattr(response, "output_text", None) or getattr(response, "text", None) or ""
            
            self.logger.info("Generated edited HTML", content_length=len(edited_html))
            
            if not edited_html:
                self.log_external_service_error("OpenAI", "edit_html", "No edited HTML generated")
                raise HTTPException(
                    status_code=500,
                    detail="No edited HTML generated by OpenAI GPT-5"
                )
            
            # Clean up the response
            edited_html = edited_html.replace("```html", "").replace("```", "")
            
            return edited_html
            
        except APIError as e:
            self.log_external_service_error("OpenAI", "edit_html", str(e))
            raise HTTPException(
                status_code=500,
                detail=f"OpenAI API error during HTML editing: {str(e)}"
            )
        except Exception as e:
            error_msg = str(e)
            self.logger.exception("Failed to edit HTML content", error_type=type(e).__name__)
            
            if "timeout" in error_msg.lower():
                raise HTTPException(
                    status_code=408,
                    detail=f"OpenAI API timeout during HTML editing: {error_msg}"
                )
            elif "connection" in error_msg.lower():
                raise HTTPException(
                    status_code=503,
                    detail=f"OpenAI API connection error during HTML editing: {error_msg}"
                )
            else:
                raise HTTPException(
                    status_code=500,
                    detail=f"OpenAI API error during HTML editing: {error_msg}"
                )

    async def convert_slide_to_html(self, image_path: str, xml_content: str, fonts: Optional[List[str]] = None) -> str:
        """
        Convert a slide image and XML to HTML.
        
        Args:
            image_path: Path to the slide image
            xml_content: OXML content
            fonts: Optional list of fonts
            
        Returns:
            Generated HTML content
        """
        self.log_request_start("convert_slide_to_html", image_path=image_path)
        
        try:
            # Get OpenAI API key
            api_key = os.getenv("OPENAI_API_KEY")
            if not api_key:
                self.log_validation_error("api_key", "missing", "OPENAI_API_KEY environment variable not set")
                raise HTTPException(
                    status_code=500, 
                    detail="OPENAI_API_KEY environment variable not set"
                )
            
            # Resolve image path to actual file system path
            if image_path.startswith("/app_data/images/"):
                relative_path = image_path[len("/app_data/images/"):]
                actual_image_path = os.path.join(get_images_directory(), relative_path)
            elif image_path.startswith("/static/"):
                relative_path = image_path[len("/static/"):]
                actual_image_path = os.path.join("static", relative_path)
            else:
                if os.path.isabs(image_path):
                    actual_image_path = image_path
                else:
                    actual_image_path = os.path.join(get_images_directory(), image_path)
            
            # Check if image file exists
            if not os.path.exists(actual_image_path):
                self.log_validation_error("image_file", "not_found", f"Image file not found: {image_path}")
                raise HTTPException(
                    status_code=404,
                    detail=f"Image file not found: {image_path}"
                )
            
            # Read and encode image
            with open(actual_image_path, "rb") as image_file:
                image_content = image_file.read()
            base64_image = base64.b64encode(image_content).decode('utf-8')
            
            # Determine media type
            file_extension = os.path.splitext(actual_image_path)[1].lower()
            media_type_map = {
                '.png': 'image/png',
                '.jpg': 'image/jpeg',
                '.jpeg': 'image/jpeg',
                '.gif': 'image/gif',
                '.webp': 'image/webp'
            }
            media_type = media_type_map.get(file_extension, 'image/png')
            
            # Generate HTML
            html_content = await self.generate_html_from_slide(
                base64_image=base64_image,
                media_type=media_type,
                xml_content=xml_content,
                api_key=api_key,
                fonts=fonts,
            )
            
            # Clean up HTML
            html_content = html_content.replace("```html", "").replace("```", "")
            
            self.log_request_success("convert_slide_to_html", html_length=len(html_content))
            return html_content
            
        except HTTPException:
            raise
        except Exception as e:
            self.log_request_error("convert_slide_to_html", e, image_path=image_path)
            raise HTTPException(
                status_code=500,
                detail=f"Error processing slide to HTML: {str(e)}"
            )

    async def convert_html_to_react(
        self, 
        html_content: str, 
        image_path: Optional[str] = None
    ) -> str:
        """
        Convert HTML content to React component.
        
        Args:
            html_content: HTML content to convert
            image_path: Optional image path for context
            
        Returns:
            Generated React component code
        """
        self.log_request_start("convert_html_to_react", html_length=len(html_content))
        
        try:
            # Get OpenAI API key
            api_key = os.getenv("OPENAI_API_KEY")
            if not api_key:
                self.log_validation_error("api_key", "missing", "OPENAI_API_KEY environment variable not set")
                raise HTTPException(
                    status_code=500, 
                    detail="OPENAI_API_KEY environment variable not set"
                )
            
            # Handle optional image for context
            image_base64 = None
            media_type = None
            
            if image_path:
                # Resolve image path similar to convert_slide_to_html
                if image_path.startswith("/app_data/images/"):
                    relative_path = image_path[len("/app_data/images/"):]
                    actual_image_path = os.path.join(get_images_directory(), relative_path)
                elif image_path.startswith("/static/"):
                    relative_path = image_path[len("/static/"):]
                    actual_image_path = os.path.join("static", relative_path)
                else:
                    actual_image_path = image_path if os.path.isabs(image_path) else os.path.join(get_images_directory(), image_path)
                
                if os.path.exists(actual_image_path):
                    with open(actual_image_path, "rb") as image_file:
                        image_content = image_file.read()
                    image_base64 = base64.b64encode(image_content).decode('utf-8')
                    
                    file_extension = os.path.splitext(actual_image_path)[1].lower()
                    media_type_map = {
                        '.png': 'image/png',
                        '.jpg': 'image/jpeg',
                        '.jpeg': 'image/jpeg',
                        '.gif': 'image/gif',
                        '.webp': 'image/webp'
                    }
                    media_type = media_type_map.get(file_extension, 'image/png')
            
            # Generate React component
            react_content = await self.generate_react_component_from_html(
                html_content=html_content,
                api_key=api_key,
                image_base64=image_base64,
                media_type=media_type
            )
            
            self.log_request_success("convert_html_to_react", react_length=len(react_content))
            return react_content
            
        except HTTPException:
            raise
        except Exception as e:
            self.log_request_error("convert_html_to_react", e)
            raise HTTPException(
                status_code=500,
                detail=f"Error processing HTML to React: {str(e)}"
            )

    async def save_layouts(self, layouts_data: List[Dict]) -> tuple[int, str]:
        """
        Save presentation layouts to database.
        
        Args:
            layouts_data: List of layout data dictionaries
            
        Returns:
            Tuple of (saved_count, message)
        """
        self.log_request_start("save_layouts", layout_count=len(layouts_data))
        
        try:
            saved_count = 0
            
            for layout_data in layouts_data:
                # Validate required fields
                self.validate_string_length(layout_data.get("presentation_id", ""), "presentation_id", min_length=1)
                self.validate_string_length(layout_data.get("layout_id", ""), "layout_id", min_length=1)
                self.validate_string_length(layout_data.get("layout_name", ""), "layout_name", min_length=1)
                self.validate_string_length(layout_data.get("layout_code", ""), "layout_code", min_length=1)
                
                # Check if layout already exists
                existing = await self.sql_session.get(
                    PresentationLayoutCodeModel,
                    (layout_data["presentation_id"], layout_data["layout_id"])
                )
                
                if existing:
                    # Update existing layout
                    existing.layout_name = layout_data["layout_name"]
                    existing.layout_code = layout_data["layout_code"]
                    existing.fonts = layout_data.get("fonts")
                    self.logger.debug("Updated existing layout", 
                                    presentation_id=layout_data["presentation_id"],
                                    layout_id=layout_data["layout_id"])
                else:
                    # Create new layout
                    new_layout = PresentationLayoutCodeModel(
                        presentation_id=layout_data["presentation_id"],
                        layout_id=layout_data["layout_id"],
                        layout_name=layout_data["layout_name"],
                        layout_code=layout_data["layout_code"],
                        fonts=layout_data.get("fonts")
                    )
                    await self.safe_add(new_layout)
                    self.logger.debug("Created new layout", 
                                    presentation_id=layout_data["presentation_id"],
                                    layout_id=layout_data["layout_id"])
                
                saved_count += 1
            
            await self.safe_commit()
            
            self.log_request_success("save_layouts", saved_count=saved_count)
            return saved_count, f"Successfully saved {saved_count} layouts"
            
        except HTTPException:
            await self.sql_session.rollback()
            raise
        except Exception as e:
            await self.sql_session.rollback()
            self.log_request_error("save_layouts", e, layout_count=len(layouts_data))
            raise HTTPException(
                status_code=500,
                detail=f"Error saving layouts: {str(e)}"
            )

    async def get_layouts(self, presentation_id: str) -> tuple[List[Dict], Optional[dict], Optional[List[str]]]:
        """
        Retrieve layouts for a presentation.
        
        Args:
            presentation_id: ID of the presentation
            
        Returns:
            Tuple of (layouts, template, fonts)
        """
        self.log_request_start("get_layouts", presentation_id=presentation_id)
        
        try:
            self.validate_string_length(presentation_id, "presentation_id", min_length=1)
            
            # Query layouts for the presentation
            result = await self.sql_session.execute(
                select(PresentationLayoutCodeModel)
                .where(PresentationLayoutCodeModel.presentation_id == presentation_id)
            )
            layout_models = result.scalars().all()
            
            layouts = []
            template = None
            fonts = None
            
            for layout_model in layout_models:
                layout_dict = {
                    "presentation_id": layout_model.presentation_id,
                    "layout_id": layout_model.layout_id,
                    "layout_name": layout_model.layout_name,
                    "layout_code": layout_model.layout_code
                }
                if layout_model.fonts:
                    layout_dict["fonts"] = layout_model.fonts
                layouts.append(layout_dict)
            
            # Get template info if available
            template_result = await self.sql_session.execute(
                select(TemplateModel).where(TemplateModel.id == presentation_id)
            )
            template_model = template_result.scalar_one_or_none()
            
            if template_model:
                template = {
                    "id": template_model.id,
                    "name": template_model.name,
                    "description": template_model.description,
                    "created_at": template_model.created_at
                }
            
            self.log_request_success("get_layouts", 
                                   presentation_id=presentation_id,
                                   layout_count=len(layouts))
            
            return layouts, template, fonts
            
        except HTTPException:
            raise
        except Exception as e:
            self.log_request_error("get_layouts", e, presentation_id=presentation_id)
            raise HTTPException(
                status_code=500,
                detail=f"Error retrieving layouts: {str(e)}"
            )

    async def get_presentations_summary(self) -> tuple[List[Dict], int, int]:
        """
        Get summary of all presentations with layout counts.
        
        Returns:
            Tuple of (presentations, total_presentations, total_layouts)
        """
        self.log_request_start("get_presentations_summary")
        
        try:
            # Query layout counts per presentation
            result = await self.sql_session.execute(
                select(
                    PresentationLayoutCodeModel.presentation_id,
                    func.count(PresentationLayoutCodeModel.layout_id).label("layout_count"),
                    func.max(PresentationLayoutCodeModel.updated_at).label("last_updated_at")
                )
                .group_by(PresentationLayoutCodeModel.presentation_id)
            )
            presentation_summaries = result.all()
            
            presentations = []
            total_layouts = 0
            
            for summary in presentation_summaries:
                presentation_id = summary.presentation_id
                layout_count = summary.layout_count
                last_updated_at = summary.last_updated_at
                total_layouts += layout_count
                
                # Get template info if available
                template_result = await self.sql_session.execute(
                    select(TemplateModel).where(TemplateModel.id == presentation_id)
                )
                template_model = template_result.scalar_one_or_none()
                
                template_info = None
                if template_model:
                    template_info = {
                        "id": template_model.id,
                        "name": template_model.name,
                        "description": template_model.description,
                        "created_at": template_model.created_at
                    }
                
                presentations.append({
                    "presentation_id": presentation_id,
                    "layout_count": layout_count,
                    "last_updated_at": last_updated_at,
                    "template": template_info
                })
            
            total_presentations = len(presentations)
            
            self.log_request_success("get_presentations_summary", 
                                   total_presentations=total_presentations,
                                   total_layouts=total_layouts)
            
            return presentations, total_presentations, total_layouts
            
        except Exception as e:
            self.log_request_error("get_presentations_summary", e)
            raise HTTPException(
                status_code=500,
                detail=f"Error retrieving presentations summary: {str(e)}"
            )

    async def create_template(self, template_id: str, name: str, description: Optional[str] = None) -> dict:
        """
        Create or update a template.
        
        Args:
            template_id: ID of the template
            name: Name of the template
            description: Optional description
            
        Returns:
            Template dictionary
        """
        self.log_request_start("create_template", template_id=template_id, name=name)
        
        try:
            self.validate_string_length(template_id, "template_id", min_length=1)
            self.validate_string_length(name, "name", min_length=1)
            
            # Check if template exists
            existing = await self.sql_session.get(TemplateModel, template_id)
            
            if existing:
                # Update existing template
                existing.name = name
                existing.description = description
                self.logger.debug("Updated existing template", template_id=template_id)
            else:
                # Create new template
                new_template = TemplateModel(
                    id=template_id, 
                    name=name, 
                    description=description
                )
                await self.safe_add(new_template)
                self.logger.debug("Created new template", template_id=template_id)
            
            await self.safe_commit()
            
            # Read back the template
            template = await self.sql_session.get(TemplateModel, template_id)
            template_dict = {
                "id": template.id,
                "name": template.name,
                "description": template.description,
                "created_at": template.created_at,
            }
            
            self.log_request_success("create_template", template_id=template_id)
            return template_dict
            
        except HTTPException:
            await self.sql_session.rollback()
            raise
        except Exception as e:
            await self.sql_session.rollback()
            self.log_request_error("create_template", e, template_id=template_id)
            raise HTTPException(
                status_code=500,
                detail=f"Error creating template: {str(e)}"
            )

    async def edit_html_with_uploaded_images(
        self,
        current_ui_image: UploadFile,
        sketch_image: Optional[UploadFile],
        html_content: str,
        prompt: str
    ) -> str:
        """
        Edit HTML content based on uploaded images and prompt.
        
        Args:
            current_ui_image: Current UI image file
            sketch_image: Optional sketch image file
            html_content: Current HTML content
            prompt: Edit instruction prompt
            
        Returns:
            Edited HTML content
        """
        self.log_request_start("edit_html_with_uploaded_images", prompt=prompt[:50])
        
        try:
            # Get OpenAI API key
            api_key = os.getenv("OPENAI_API_KEY")
            if not api_key:
                self.log_validation_error("api_key", "missing", "OPENAI_API_KEY environment variable not set")
                raise HTTPException(
                    status_code=500, 
                    detail="OPENAI_API_KEY environment variable not set"
                )
            
            # Validate inputs
            self.validate_string_length(html_content, "html_content", min_length=1, max_length=100000)
            self.validate_string_length(prompt, "prompt", min_length=1, max_length=2000)
            
            # Validate current UI image
            if not current_ui_image.content_type or not current_ui_image.content_type.startswith("image/"):
                self.log_validation_error("current_ui_image", "invalid_type", "File must be an image")
                raise HTTPException(
                    status_code=400,
                    detail="Current UI file must be an image"
                )
            
            # Validate sketch image if provided
            if sketch_image and (not sketch_image.content_type or not sketch_image.content_type.startswith("image/")):
                self.log_validation_error("sketch_image", "invalid_type", "File must be an image")
                raise HTTPException(
                    status_code=400,
                    detail="Sketch file must be an image"
                )
            
            # Read and encode current UI image
            current_ui_content = await current_ui_image.read()
            current_ui_base64 = base64.b64encode(current_ui_content).decode('utf-8')
            
            # Read and encode sketch image if provided
            sketch_base64 = None
            if sketch_image:
                sketch_content = await sketch_image.read()
                sketch_base64 = base64.b64encode(sketch_content).decode('utf-8')
            
            media_type = current_ui_image.content_type
            
            # Edit HTML using the existing method
            edited_html = await self.edit_html_with_images(
                current_ui_base64=current_ui_base64,
                sketch_base64=sketch_base64,
                media_type=media_type,
                html_content=html_content,
                prompt=prompt,
                api_key=api_key
            )
            
            # Clean up response
            edited_html = edited_html.replace("```html", "").replace("```", "")
            
            self.log_request_success("edit_html_with_uploaded_images", edited_html_length=len(edited_html))
            return edited_html
            
        except HTTPException:
            raise
        except Exception as e:
            self.log_request_error("edit_html_with_uploaded_images", e, prompt=prompt[:50])
            raise HTTPException(
                status_code=500,
                detail=f"Error processing HTML editing: {str(e)}"
            )